### ISSUE TITLE
Upgrade to breeze-client 2.0

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze.js.labs#43]
Can this be upgraded to work along with breeze-client 2.0.

We need getEntityGraph to work with breeze-client 2.0 and Angular 8.

Thank you !

**Comment by rrajewski** [comment]
We use enableSaveQueuing, could that be upgraded as well?

**Comment by steveschmitt** [comment]
I'm working on these now.

**Comment by steveschmitt** [comment]
Added both `getEntityGraph` and `enableSaveQueuing` in breeze-client 2.0.1.

Please see the [Release Notes](http://breeze.github.io/doc-js/release-notes.html) for usage, because enabling these mixins is different now.

The big problem was that Production builds were tree-shaking the mixins away, so they had to be changed to prevent that.

**Comment by graphicsxp** [comment]
Awesome. Now I can get rid of my custom getEntityGraph package and start using the breeze one again :)
